// Code generated by protoc-gen-go.
// source: vch.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	vch.proto

It has these top-level messages:
	NLPResponse
	TunnelRequest
	TunnelResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NLPResponse struct {
	Body []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *NLPResponse) Reset()                    { *m = NLPResponse{} }
func (m *NLPResponse) String() string            { return proto.CompactTextString(m) }
func (*NLPResponse) ProtoMessage()               {}
func (*NLPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NLPResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type TunnelRequest struct {
}

func (m *TunnelRequest) Reset()                    { *m = TunnelRequest{} }
func (m *TunnelRequest) String() string            { return proto.CompactTextString(m) }
func (*TunnelRequest) ProtoMessage()               {}
func (*TunnelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TunnelResponse struct {
	// Types that are valid to be assigned to Event:
	//	*TunnelResponse_Response
	Event isTunnelResponse_Event `protobuf_oneof:"event"`
}

func (m *TunnelResponse) Reset()                    { *m = TunnelResponse{} }
func (m *TunnelResponse) String() string            { return proto.CompactTextString(m) }
func (*TunnelResponse) ProtoMessage()               {}
func (*TunnelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isTunnelResponse_Event interface {
	isTunnelResponse_Event()
}

type TunnelResponse_Response struct {
	Response *NLPResponse `protobuf:"bytes,1,opt,name=response,oneof"`
}

func (*TunnelResponse_Response) isTunnelResponse_Event() {}

func (m *TunnelResponse) GetEvent() isTunnelResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *TunnelResponse) GetResponse() *NLPResponse {
	if x, ok := m.GetEvent().(*TunnelResponse_Response); ok {
		return x.Response
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TunnelResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TunnelResponse_OneofMarshaler, _TunnelResponse_OneofUnmarshaler, _TunnelResponse_OneofSizer, []interface{}{
		(*TunnelResponse_Response)(nil),
	}
}

func _TunnelResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TunnelResponse)
	// event
	switch x := m.Event.(type) {
	case *TunnelResponse_Response:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Response); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TunnelResponse.Event has unexpected type %T", x)
	}
	return nil
}

func _TunnelResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TunnelResponse)
	switch tag {
	case 1: // event.response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NLPResponse)
		err := b.DecodeMessage(msg)
		m.Event = &TunnelResponse_Response{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TunnelResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TunnelResponse)
	// event
	switch x := m.Event.(type) {
	case *TunnelResponse_Response:
		s := proto.Size(x.Response)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*NLPResponse)(nil), "pb.NLPResponse")
	proto.RegisterType((*TunnelRequest)(nil), "pb.TunnelRequest")
	proto.RegisterType((*TunnelResponse)(nil), "pb.TunnelResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for VCH service

type VCHClient interface {
	Tunnel(ctx context.Context, in *TunnelRequest, opts ...grpc.CallOption) (VCH_TunnelClient, error)
}

type vCHClient struct {
	cc *grpc.ClientConn
}

func NewVCHClient(cc *grpc.ClientConn) VCHClient {
	return &vCHClient{cc}
}

func (c *vCHClient) Tunnel(ctx context.Context, in *TunnelRequest, opts ...grpc.CallOption) (VCH_TunnelClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_VCH_serviceDesc.Streams[0], c.cc, "/pb.VCH/Tunnel", opts...)
	if err != nil {
		return nil, err
	}
	x := &vCHTunnelClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VCH_TunnelClient interface {
	Recv() (*TunnelResponse, error)
	grpc.ClientStream
}

type vCHTunnelClient struct {
	grpc.ClientStream
}

func (x *vCHTunnelClient) Recv() (*TunnelResponse, error) {
	m := new(TunnelResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for VCH service

type VCHServer interface {
	Tunnel(*TunnelRequest, VCH_TunnelServer) error
}

func RegisterVCHServer(s *grpc.Server, srv VCHServer) {
	s.RegisterService(&_VCH_serviceDesc, srv)
}

func _VCH_Tunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TunnelRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VCHServer).Tunnel(m, &vCHTunnelServer{stream})
}

type VCH_TunnelServer interface {
	Send(*TunnelResponse) error
	grpc.ServerStream
}

type vCHTunnelServer struct {
	grpc.ServerStream
}

func (x *vCHTunnelServer) Send(m *TunnelResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _VCH_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VCH",
	HandlerType: (*VCHServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Tunnel",
			Handler:       _VCH_Tunnel_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vch.proto",
}

func init() { proto.RegisterFile("vch.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4b, 0xce, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe4, 0xe2, 0xf6, 0xf3, 0x09,
	0x08, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe2, 0x62, 0x49, 0xca, 0x4f, 0xa9,
	0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x95, 0xf8, 0xb9, 0x78, 0x43, 0x4a, 0xf3,
	0xf2, 0x52, 0x73, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0x3c, 0xb8, 0xf8, 0x60, 0x02,
	0x50, 0x6d, 0xba, 0x5c, 0x1c, 0x45, 0x50, 0x36, 0x58, 0x2b, 0xb7, 0x11, 0xbf, 0x5e, 0x41, 0x92,
	0x1e, 0x92, 0xc9, 0x1e, 0x0c, 0x41, 0x70, 0x25, 0x4e, 0xec, 0x5c, 0xac, 0xa9, 0x65, 0xa9, 0x79,
	0x25, 0x46, 0x56, 0x5c, 0xcc, 0x61, 0xce, 0x1e, 0x42, 0xc6, 0x5c, 0x6c, 0x10, 0x03, 0x85, 0x04,
	0x41, 0xda, 0x50, 0x6c, 0x93, 0x12, 0x42, 0x16, 0x82, 0x18, 0xa0, 0xc4, 0x60, 0xc0, 0x98, 0xc4,
	0x06, 0xf6, 0x84, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x96, 0x9f, 0x69, 0xd1, 0x00, 0x00,
	0x00,
}
